[[redirects]]  
from = "/*"  
to = "/index.html"  
status = 200

[[headers]]
  for = "/*.json.gz"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.prbm.gz"
  [headers.values]
    Content-Encoding = "gzip"
