name: BlueMap - Render Test Server

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - TestServer

jobs:
  render:
    name: Render - Test Server
    uses: EfinaServer/bluemap-action/.github/workflows/bluemap.yml@dev
    with:
      runner_name: "ubuntu-latest"
      workdir_path: "TestServer"
      maps_list: "world world_nether world_the_end"
      mc_version: "1.21.1"
      s3_provider: "vultr"
      s3_region: "sgp1"
      site_name: "EfinaNetwork"
      site_content: "Minecraft 1.21.1｜測試網站"
      site_title: "一個可愛測試網站"
      site_date_time: "2024/07/22 ~ 2024/08/27"
    secrets:
      PTERODACTYL_API_URL: ${{ secrets.PTERODACTYL_API_URL }}
      PTERODACTYL_API_TOKEN: ${{ secrets.PTERODACTYL_API_TOKEN }}
      PTERODACTYL_ID: ${{ secrets.PTERODACTYL_TESTSERVER_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_TESTSERVER_SITE_ID }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
